### ISSUE TITLE
Chapter 7 demo fails to compile due to missing file

### ISSUE THREAD

**Issue by xty** [OpenGLInsights/OpenGLInsightsCode#12]
It seems the issues in this repo are not being monitored, but I will post it here anyway for the lack of a more appropriate place.

When I compile the codes in both demo1 and demo2 using GNU Make, the following error occur:
```
$ make Linux
gcc -I. -I/usr/include shaderdemo.c -lglfw -lGLU -o shaderdemo
In file included from shaderdemo.c:29:0:
./GL/glfw.h:162:20: fatal error: GL/gl.h: No such file or directory
compilation terminated.
Makefile:11: recipe for target 'Linux' failed
make: *** [Linux] Error 1
```

It appears `GL/gl.h` is needed for compilation but is missing for some reason.

**Comment by xty** [comment]
@stegu

**Comment by stegu** [comment]
This is a problem with your OpenGL configuration. In the Makefile, you need
to specify the search path to where your GL directory is installed locally.
